[tox]
envlist = lint,testenv
skipsdist = true

[testenv]
deps = -rrequirements.txt
       pytest
commands = pytest

[testenv:lint]
deps = flake8
       flake8-import-order
       flake8-blind-except
       flake8-builtins
       flake8-docstrings
       flake8-rst-docstrings
       flake8-logging-format
       pydocstyle < 4.0.0
       pytest

commands = flake8 {posargs}

[flake8]
show-source = true

ignore =
  # B001 do not use bare except, specify exception instead
  B001,
  # B901 blind except: statement
  B901,
  # D100 Missing docstring in public module
  D100,
  # D101 Missing docstring in public class
  D101,
  # D102 Missing docstring in public method
  D102,
  # D103 Missing docstring in public function
  D103,
  # D104 Missing docstring in public package
  D104,
  # D105 Missing docstring in magic method
  D105,
  # D107 Missing docstring in __init__
  D107,
  # E722 do not use bare except, specify exception instead
  E722,
  # G200 Logging statement uses exception in arguments
  G200
  # C901 Method is too complex
  C901
  # B902 blind except
  B902

max-line-length = 120
max-complexity = 16

exclude = 
  .tox
  .git
  build
  venv/*  
  doc
  *.eff  
  __pycache__

enable-extensions=G
application-import-names = kube-opex-analytics
